runtime: python27 # or another supported version
threadsafe: false

instance_class: F2

handlers:
- url: /
  script: service.py

- url: /search/movie
  script: service.py

- url: /upload/movie
  script: service.py